repos:
  - repo: local
    hooks:
      - id: run-smoke-tests
        name: Run smoke tests
        entry: pytest tests/smoke/ -v
        language: system
        pass_filenames: false
        stages: [commit]
      
      - id: run-integration-tests
        name: Run integration tests
        entry: pytest tests/integration/ -v
        language: system
        pass_filenames: false
        stages: [commit]
        
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        language_version: python3
        
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [--max-line-length=88, --extend-ignore=E203,W503]
