name: Test Suite

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-qt pytest-cov
    
    - name: Run smoke tests
      run: pytest tests/smoke/ -v --tb=short
    
    - name: Run unit tests
      run: pytest tests/unit/ -v --tb=short
      continue-on-error: true
    
    - name: Run integration tests
      run: pytest tests/integration/ -v --tb=short
    
    - name: Generate coverage report
      run: pytest --cov=. --cov-report=xml --cov-report=term tests/smoke/ tests/integration/
      continue-on-error: true
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
